### ISSUE TITLE
Can not add text to Study

### ISSUE THREAD

**Issue by rsalek** [althonos/mzml2isa-qt#1]
I tried "pip3 install mzml2isa-qt --upgrade" all seems updated.
Successfully installed PyQt5-5.7 lxml-3.6.1 mzml2isa-0.4.23 mzml2isa-qt-0.3.0 pronto-0.3.2 sip-4.18.1

However I still can't enter any text in "Study name" or browse "Out put folder"
"About" and "Help "buttons don't seems to work either.

**Comment by althonos** [comment]
About and help button (and windows) are not implémentés yet.
For the study name, is it the study name field in the "Additional metadata..." window or in the main program window ?
I'll investigateurs the output folder button.

**Comment by althonos** [comment]
@rsalek see commit 40748c539516eda01ec59e31444e32c48a81d998 and version **0.3.1**, the help button now opens the browser at the online doc page for each GUI flavour.

**Comment by rsalek** [comment]
Nice, so that and works well. I still get the "KeyError: 'unitCvRef' BTW on the command line version. Also can not input the study name.

**Comment by althonos** [comment]
@rsalek are you sure you unchecked the checkbox like I put before ? When testing on my computer it works

**Comment by rsalek** [comment]
Also can you change "Export result to directory of each study option " not to be the default ? so can be ticked in needed.

**Comment by rsalek** [comment]
I realised my mistake :)

**Comment by althonos** [comment]
No problem :)
Still should we leave it as default or not ? Back in July we decided to leave the checkbox checked as default, but we could change that

**Comment by rsalek** [comment]
Better to unchecked, also just ran it and got:
An error was encountered while parsing tiny.msdata.mzML0.99.10.mzML:
KeyError 'unitCvRef'

**Comment by althonos** [comment]
Actually, the **tiny.msdata.mzML0.99.10.mzML** file may go against the mzML specification, although I'm not sure: here's the incriminated line:

```xml
<cvParam cvRef="MS" accession="MS:1000016" name="scan time" value="5.8905" unitAccession="MS:1000038" unitName="minute"/>
```

This block has a unitName and a unitAccession attribute, but no unitCvRef attribute. In all the other files I parsed, whenever a cvParam had a unit, it would contain the three following attributes: **unitName**, **unitAccession**, **unitCvRef**.

I'm opening an issue here : https://github.com/althonos/mzml2isa/issues/13
