### ISSUE TITLE
saving authors details with in Windows 

### ISSUE THREAD

**Issue by rsalek** [althonos/mzml2isa-qt#4]
While using the mzml2isa-qt in Windows, if you add authors details and try to save it, the application will close/crash. I will try to give you more information but the person with Windows machine not here today.

**Comment by althonos** [comment]
Hi Reza,
this was also the case with linux actually, I tweaked the name of some variables and forgot to apply the changes everywhere. This should hopefully be fixed in f7d465e397fbdab296793ba66b656255f8f37075.
